version: "0.1"
name: elm_app
services:
  Frontend:
    image: elm-app
    build:
      context: .
    volumes:
      - .:/app/elm-app
    container_name: elm-http-builder
    ports:
      - 2300:3000
